name: modlitebni_app
description: "Modlitební aplikace s WYSIWYG editorem"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 🔧 Aplikace
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  html: ^0.15.4
  share_plus: ^10.0.2
  html_editor_enhanced: ^2.6.0
  flutter_html: ^3.0.0
  gesture_x_detector: ^1.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/mse.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/texts/
    - assets/moznosti.txt
